"""Create initial tables

Revision ID: 5d6e0a745cf2
Revises: 
Create Date: 2025-11-05 16:01:51.203298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6e0a745cf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('smoker', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('predicted_charge', sa.Float(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_predictions_client_ip'), 'medical_predictions', ['client_ip'], unique=False)
    op.create_index(op.f('ix_medical_predictions_id'), 'medical_predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_predictions_id'), table_name='medical_predictions')
    op.drop_index(op.f('ix_medical_predictions_client_ip'), table_name='medical_predictions')
    op.drop_table('medical_predictions')
    # ### end Alembic commands ###
