optuna:
  trials: 20

RandomForestRegressor:
  n_estimators:
    min: 50
    max: 150
    step: 10
  max_depth:
    min: 2
    max: 15
  min_samples_split:
    min: 2
    max: 10
  min_samples_leaf:
    min: 2
    max: 10

DecisionTreeRegressor:
  max_depth:
    min: 2
    max: 15
  min_samples_split:
    min: 2
    max: 10
  min_samples_leaf:
    min: 2
    max: 10

KNeighborsRegressor:
  n_neighbors:
    min: 3
    max: 10
    step: 1
  leaf_size:
    min: 10
    max: 40
    step: 5
  p:
    - 1
    - 2
  weights:
    choices: 
     - uniform
     - distance
